### ISSUE TITLE
Missing config in app.js

### ISSUE THREAD

**Issue by appieschot** [zoom/videosdk-ui-toolkit-react-sample#2]
If you clone the solution and follow the readme.md the experience fails and loads a blank screen. If you open the Developer experience you find that the console nicely writes out a 400 error on the localhost:4000, even though it is running, and the parameters are passed on

```json
{
    "errors": [
        {
            "property": "role",
            "reason": "Property required, but not present in request body"
        },
        {
            "property": "sessionName",
            "reason": "Property required, but not present in request body"
        }
    ]
}
```

You can solve this by adding a line containing ` headers: { 'Content-Type': 'application/json' }` in the `app.ts` : resulting in the following: 

```ts
    fetch(authEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionName:  config.sessionName,
```

**Comment by tommygaessler** [comment]
Thank you @appieschot . 

I think it depends on your endpoint setup and if you have to explicitly set the content type, or `JSON.stringify()`, etc.

Can you share more details about it so we can look into supporting as many endpoint configs out of the box?

**Comment by appieschot** [comment]
@tommygaessler, sure it has to do with the endpoint setup, but I am just following the `official docs` as provided in the samples, hence I am a bit confused. 

I did the following: 

- I cloned this repo
- ran `npm install`
- navigated to https://github.com/zoom/videosdk-auth-endpoint-sample
- cloned that repo 
- ran `npm install`
- put in the `.env` file 
- ran `npm start`
- went back to the first cloned repo
- put in `http://localhost:4000` in the `src/app.js` file 
- ran `npm start`

With that you get the exact error when you navigate to http://localhost:3000/ and click "Join Session".

Running on Windows 11 with WSL, Node v18.19.0 through nvm.

Hope this helps

**Comment by EkaanshArora** [comment]
Hey @tommygaessler, I'm able to reproduce the error @appieschot posted.
Adding `'Content-Type': 'application/json'` to the header works with https://github.com/zoom/videosdk-auth-endpoint-sample.

**Comment by tommygaessler** [comment]
Got it thank you @EkaanshArora , @appieschot , we will update the samples to include the header.
