### ISSUE TITLE
Getting Started with UI Toolkit quick start for React

### ISSUE THREAD

**Issue by adriangritz** [zoom/videosdk-ui-toolkit-react-sample#6]
<img width="1167" alt="ui-toolkit-react-error" src="https://github.com/user-attachments/assets/eedffd6c-bd5b-4a97-addc-a3bee18c6190">

I am trying to follow the UI Toolkit quick start for React, but I am getting the error above. Do you have any suggestions?

**Comment by Fashad-Ahmed** [comment]
@adriangritz I've cloned the repo, it's working fine on my machine. Can you please elaborate the context of what you have done up till now?

**Comment by adriangritz** [comment]
No worries. It's likely my lack of expertise. Please feel free to close out
the issue. I realize I must use the SDK version anyway.

Take care,

Adrian

**Comment by tommygaessler** [comment]
Glad to hear you were able to sort out the issue @adriangritz . Thanks for your support @Fashad-Ahmed .
